apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-var-test
  namespace: openshift-gitopsspec
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: env-var-test
    repoURL: 'https://github.com/strangiato/kustomize-env-test.git'
    targetRevision: HEAD
